export type SeedGenreEntry = {
  canonicalGenre: string;
  aliases: string[];
  seedArtists: string[];
  relatedArtists: string[];
  starterSongs?: string[];
  subgenres?: string[];
  moods?: string[];
  eras?: string[];
  avoidTerms?: string[];
  notes?: string;
};

export const GENRE_SEED_MAP: Record<string, SeedGenreEntry> = {
  "tropical house": {
    canonicalGenre: "Tropical House",
    aliases: ["trop house", "tropical pop", "tropical dance", "tropical edm"],
    seedArtists: ["Kygo", "Thomas Jack", "Sam Feldt", "Lost Frequencies", "Klingande", "Robin Schulz", "Matoma"],
    relatedArtists: ["Felix Jaehn", "Sigala", "Jonas Blue", "Bakermat", "FDVM"],
    starterSongs: ["Firestone - Kygo", "Stolen Dance - Milky Chance (Robin Schulz Remix)", "Show Me Love - Sam Feldt", "Jubel - Klingande", "Are You With Me - Lost Frequencies"],
    moods: ["sunny", "uplifting", "beach", "warm", "breezy"],
    eras: ["2014–present"],
    avoidTerms: ["workout mix", "best of tropical", "meditation music"],
    notes: "Soft, melodic dance music with steel drums, marimbas, and summery textures. Emerged mid-2010s."
  },
  "deep house": {
    canonicalGenre: "Deep House",
    aliases: ["deep", "deep tech", "deep electronic"],
    seedArtists: ["Larry Heard", "Kerri Chandler", "Maya Jane Coles", "Dusky", "Disclosure", "Hot Since 82", "Lane 8"],
    relatedArtists: ["Eats Everything", "Bicep", "Anjunadeep artists", "Ben Böhmer", "Yotto"],
    starterSongs: ["Can You Feel It - Mr. Fingers", "Rain - Kerri Chandler", "White Noise - Disclosure", "Midnight - Lane 8"],
    subgenres: ["deep tech house", "organic house"],
    moods: ["warm", "hypnotic", "nocturnal", "groovy"],
    eras: ["1986–present"],
    avoidTerms: ["deep house mix 2024", "deep relaxation", "deep sleep"],
    notes: "Deeper, moodier offshoot of Chicago house. Warm pads, sub-bass, and understated vocals."
  },
  "soulful house": {
    canonicalGenre: "Soulful House",
    aliases: ["vocal house", "soulful deep house", "gospel house"],
    seedArtists: ["Louie Vega", "Kenny Dope", "Kerri Chandler", "DJ Spen", "Frankie Knuckles", "Ron Carroll", "MK"],
    relatedArtists: ["Barbara Tucker", "Monique Bingham", "Dawn Tallman", "Joey Negro", "Defected Records artists"],
    starterSongs: ["Finally - Kings of Tomorrow", "The Whistle Song - Frankie Knuckles", "Your Love - Frankie Knuckles", "Always - MK"],
    moods: ["uplifting", "warm", "joyful", "spiritual"],
    eras: ["1990–present"],
    avoidTerms: ["soul music", "neo-soul"],
    notes: "House music centered on gospel and soul vocal performances over deep grooves."
  },
  "jazzy house": {
    canonicalGenre: "Jazzy House",
    aliases: ["jazz house", "jazzy deep house", "nu jazz house"],
    seedArtists: ["St Germain", "Bob Sinclar", "Jazzanova", "MAW (Masters at Work)", "Roni Size", "Bugz in the Attic"],
    relatedArtists: ["4hero", "Atjazz", "Louie Vega", "Henrik Schwarz", "Karizma"],
    starterSongs: ["Rose Rouge - St Germain", "I Feel for You - Bob Sinclar", "Gypsymen - Hear the Music"],
    moods: ["smooth", "sophisticated", "groovy", "late-night"],
    eras: ["1995–present"],
    avoidTerms: ["smooth jazz", "jazz standards"],
  },
  "afro house": {
    canonicalGenre: "Afro House",
    aliases: ["afrohouse", "african house", "afro tech", "afro deep"],
    seedArtists: ["Black Coffee", "Culoe De Song", "Da Capo", "Enoo Napa", "Shimza", "Caiiro"],
    relatedArtists: ["Kususa", "Sun-El Musician", "Themba", "Mzansi house artists", "Floyd Lavine"],
    starterSongs: ["Drive - Black Coffee feat. David Guetta & Delilah Montagu", "Superman - Black Coffee feat. Bucie", "10 Missed Calls - Black Coffee & Pharrell Williams"],
    moods: ["percussive", "spiritual", "driving", "tribal"],
    eras: ["2010–present"],
    avoidTerms: ["afrobeats", "afropop"],
    notes: "South African-rooted house with deep percussion, chanted vocals, and spiritual energy. Distinct from West African afrobeats."
  },
  "melodic house": {
    canonicalGenre: "Melodic House",
    aliases: ["melodic house and techno", "organic house", "indie dance"],
    seedArtists: ["Ben Böhmer", "Rufus Du Sol", "Lane 8", "Yotto", "Nora En Pure", "Tinlicker"],
    relatedArtists: ["Enamour", "Luttrell", "Monolink", "Joris Voorn", "Jan Blomqvist"],
    starterSongs: ["Beyond Beliefs - Ben Böhmer", "Innerbloom - Rufus Du Sol", "Brightest Lights - Lane 8", "Nova - Yotto"],
    moods: ["euphoric", "dreamy", "cinematic", "warm"],
    eras: ["2016–present"],
    avoidTerms: ["meditation", "best of melodic"],
  },
  "progressive house": {
    canonicalGenre: "Progressive House",
    aliases: ["prog house", "progressive", "proggy"],
    seedArtists: ["Sasha", "John Digweed", "Hernan Cattaneo", "Guy J", "Eric Prydz", "Deadmau5", "Jeremy Olander"],
    relatedArtists: ["Cid Inc", "Grum", "Cristoph", "Anjunabeats artists", "Henry Saiz"],
    starterSongs: ["Strobe - Deadmau5", "Opus - Eric Prydz", "Xpander - Sasha"],
    moods: ["hypnotic", "building", "euphoric", "trance-adjacent"],
    eras: ["1992–present"],
    avoidTerms: ["progressive rock", "prog rock"],
  },
  "techno": {
    canonicalGenre: "Techno",
    aliases: ["detroit techno", "techno music"],
    seedArtists: ["Jeff Mills", "Carl Craig", "Richie Hawtin", "Adam Beyer", "Nina Kraviz", "Amelie Lens", "Charlotte de Witte"],
    relatedArtists: ["Ben Klock", "Marcel Dettmann", "Kobosil", "Rødhåd", "Dax J"],
    starterSongs: ["The Bells - Jeff Mills", "Spastik - Plastikman", "Bug in the Bass Bin - Innerzone Orchestra"],
    subgenres: ["detroit techno", "berlin techno", "industrial techno", "hard techno", "dub techno"],
    moods: ["dark", "driving", "industrial", "hypnotic", "relentless"],
    eras: ["1985–present"],
    avoidTerms: ["techno remix", "techno workout"],
    notes: "Broad genre rooted in Detroit. Entry covers the wide spectrum; see melodic techno and minimal techno for specifics."
  },
  "melodic techno": {
    canonicalGenre: "Melodic Techno",
    aliases: ["melodic techno and house", "emotive techno"],
    seedArtists: ["Tale Of Us", "Stephan Bodzin", "Maceo Plex", "Adriatique", "Afterlife artists", "Mind Against"],
    relatedArtists: ["Colyn", "Mathame", "Kevin de Vries", "Massano", "Anyma"],
    starterSongs: ["Powers of Ten - Stephan Bodzin", "Realm of Consciousness - Tale Of Us", "Solitary Daze - Maceo Plex"],
    moods: ["cinematic", "dark", "euphoric", "emotive"],
    eras: ["2015–present"],
    avoidTerms: ["melodic dubstep"],
  },
  "minimal techno": {
    canonicalGenre: "Minimal Techno",
    aliases: ["minimal", "minimal tech", "micro house", "mnml"],
    seedArtists: ["Richie Hawtin", "Ricardo Villalobos", "Zip", "Luciano", "Magda", "Petre Inspirescu"],
    relatedArtists: ["Rhadoo", "Raresh", "Dan Andrei", "Praslea", "Sonja Moonear"],
    starterSongs: ["Spastik - Plastikman", "Fizheuer Zansen - Ricardo Villalobos"],
    moods: ["hypnotic", "stripped-back", "cerebral", "late-night"],
    eras: ["1995–present"],
    avoidTerms: ["minimalist music", "minimal classical"],
  },
  "trance": {
    canonicalGenre: "Trance",
    aliases: ["trance music", "vocal trance", "uplifting trance"],
    seedArtists: ["Armin van Buuren", "Above & Beyond", "Paul van Dyk", "Ferry Corsten", "Tiësto", "Gareth Emery"],
    relatedArtists: ["Aly & Fila", "Andrew Rayel", "Giuseppe Ottaviani", "Cosmic Gate", "Markus Schulz"],
    starterSongs: ["Adagio for Strings - Tiësto", "Sun & Moon - Above & Beyond", "Satellite - Oceanlab"],
    subgenres: ["uplifting trance", "vocal trance", "psytrance", "goa trance", "progressive trance"],
    moods: ["euphoric", "uplifting", "emotional", "epic"],
    eras: ["1991–present"],
    avoidTerms: ["trance meditation", "hypnosis"],
  },
  "drum and bass": {
    canonicalGenre: "Drum and Bass",
    aliases: ["dnb", "d&b", "d'n'b", "jungle"],
    seedArtists: ["Andy C", "Goldie", "Noisia", "Chase & Status", "Sub Focus", "Pendulum", "Netsky"],
    relatedArtists: ["Shy FX", "DJ Marky", "Wilkinson", "Dimension", "Camo & Krooked"],
    starterSongs: ["Hold Your Colour - Pendulum", "Innerspace - Goldie", "No One Knows - Sub Focus", "Tarantula - Pendulum"],
    subgenres: ["liquid dnb", "neurofunk", "jump up", "jungle"],
    moods: ["energetic", "intense", "dark", "driving"],
    eras: ["1992–present"],
    avoidTerms: ["drum solo", "drum lesson"],
  },
  "liquid drum and bass": {
    canonicalGenre: "Liquid Drum and Bass",
    aliases: ["liquid dnb", "liquid d&b", "liquid funk"],
    seedArtists: ["Calibre", "High Contrast", "London Elektricity", "Netsky", "LSB", "Etherwood"],
    relatedArtists: ["Fred V & Grafix", "Maduk", "BCee", "Makoto", "Keeno"],
    starterSongs: ["Return of Forever - High Contrast", "Memory Lane - Netsky", "Just One Second - London Elektricity"],
    moods: ["uplifting", "smooth", "melodic", "warm"],
    eras: ["2000–present"],
    avoidTerms: ["liquid dubstep"],
    notes: "The melodic, jazz-inflected side of drum and bass. Emphasis on musicality over aggression."
  },
  "garage": {
    canonicalGenre: "Garage",
    aliases: ["speed garage", "2-step garage", "2-step", "ukg"],
    seedArtists: ["MJ Cole", "Todd Edwards", "El-B", "Wookie", "Artful Dodger", "Craig David"],
    relatedArtists: ["Disclosure", "Conducta", "DJ Q", "Sunship", "Zed Bias"],
    starterSongs: ["Born to Do It - Craig David", "Re-Rewind - Artful Dodger", "Sincere - MJ Cole"],
    moods: ["skippy", "groovy", "nocturnal", "soulful"],
    eras: ["1996–present"],
    avoidTerms: ["garage rock", "garage band"],
    notes: "UK-born dance music with shuffling rhythms and R&B vocals. See also 'uk garage'."
  },
  "uk garage": {
    canonicalGenre: "UK Garage",
    aliases: ["ukg", "2step", "speed garage"],
    seedArtists: ["MJ Cole", "Artful Dodger", "Todd Edwards", "Wookie", "DJ EZ", "Tuff Jam"],
    relatedArtists: ["Craig David", "Conducta", "Interplanetary Criminal", "DJ Q", "Disclosure"],
    starterSongs: ["Sincere - MJ Cole", "Re-Rewind - Artful Dodger", "Battle - Wookie"],
    moods: ["skippy", "energetic", "soulful", "bouncy"],
    eras: ["1994–present"],
    avoidTerms: ["garage rock", "garage punk"],
  },
  "house": {
    canonicalGenre: "House",
    aliases: ["house music", "classic house", "chicago house"],
    seedArtists: ["Frankie Knuckles", "Marshall Jefferson", "Larry Heard", "Disclosure", "MK", "Armand Van Helden", "Daft Punk"],
    relatedArtists: ["Green Velvet", "The Martinez Brothers", "Fisher", "Chris Lake", "Lee Foss"],
    starterSongs: ["Your Love - Frankie Knuckles", "Move Your Body - Marshall Jefferson", "One More Time - Daft Punk", "Latch - Disclosure"],
    subgenres: ["deep house", "tech house", "acid house", "funky house", "vocal house"],
    moods: ["groovy", "uplifting", "danceable", "warm"],
    eras: ["1984–present"],
    avoidTerms: ["house cleaning", "house tour"],
    notes: "The root genre of modern dance music. This entry is broad and beginner-friendly."
  },
  "disco house": {
    canonicalGenre: "Disco House",
    aliases: ["nu disco house", "disco-infused house", "filtered house"],
    seedArtists: ["Daft Punk", "Purple Disco Machine", "Dimitri from Paris", "Aeroplane", "Chromeo"],
    relatedArtists: ["Breakbot", "Tensnake", "Todd Terje", "Joey Negro", "Yuksek"],
    starterSongs: ["Around the World - Daft Punk", "Fireworks - Purple Disco Machine", "Inspector Norse - Todd Terje"],
    moods: ["funky", "groovy", "retro", "feel-good"],
    eras: ["1998–present"],
    avoidTerms: ["disco classics", "70s disco"],
  },
  "french house": {
    canonicalGenre: "French House",
    aliases: ["french touch", "filter house", "nu disco french"],
    seedArtists: ["Daft Punk", "Cassius", "Étienne de Crécy", "Alan Braxe", "DJ Falcon"],
    relatedArtists: ["Stardust", "Modjo", "Justice", "Breakbot", "Kavinsky"],
    starterSongs: ["Music Sounds Better with You - Stardust", "Lady (Hear Me Tonight) - Modjo", "Da Funk - Daft Punk"],
    moods: ["funky", "filtered", "warm", "retro-futuristic"],
    eras: ["1996–2005", "revivals ongoing"],
    avoidTerms: ["french pop", "chanson"],
    notes: "Heavily filtered disco samples, phaser effects, and compressed grooves. Paris-born late 90s movement."
  },
  "lo-fi house": {
    canonicalGenre: "Lo-Fi House",
    aliases: ["lofi house", "raw house", "outsider house"],
    seedArtists: ["DJ Seinfeld", "Ross From Friends", "Mall Grab", "Baltra", "DJ Boring"],
    relatedArtists: ["Palms Trax", "Folamour", "Soulwax", "Chaos in the CBD", "Hank Jackson"],
    starterSongs: ["U - DJ Seinfeld", "Talk to Me You'll Understand - Ross From Friends", "Sun Chariot - Mall Grab"],
    moods: ["nostalgic", "hazy", "warm", "lo-fi"],
    eras: ["2015–present"],
    avoidTerms: ["lo-fi beats", "lo-fi hip hop"],
  },
  "k-pop": {
    canonicalGenre: "K-Pop",
    aliases: ["kpop", "korean pop", "k pop"],
    seedArtists: ["BTS", "BLACKPINK", "Stray Kids", "aespa", "NewJeans", "TWICE", "EXO", "Red Velvet"],
    relatedArtists: ["IVE", "LE SSERAFIM", "NCT", "ATEEZ", "ITZY", "(G)I-DLE"],
    starterSongs: ["Dynamite - BTS", "DDU-DU DDU-DU - BLACKPINK", "Super Shy - NewJeans", "Next Level - aespa", "Cheer Up - TWICE"],
    subgenres: ["k-hip-hop", "k-r&b", "k-indie"],
    moods: ["energetic", "polished", "catchy", "dynamic"],
    eras: ["1990s–present"],
    avoidTerms: ["k-drama ost", "korean drama"],
    notes: "Broad, beginner-friendly entry. K-pop spans many sub-styles; this highlights globally visible acts."
  },
  "j-pop": {
    canonicalGenre: "J-Pop",
    aliases: ["jpop", "japanese pop", "j pop"],
    seedArtists: ["Hikaru Utada", "Kenshi Yonezu", "YOASOBI", "Ado", "Official HIGE DANdism", "Perfume"],
    relatedArtists: ["King Gnu", "Vaundy", "imase", "Fujii Kaze", "Mrs. GREEN APPLE"],
    starterSongs: ["Idol - YOASOBI", "Lemon - Kenshi Yonezu", "New Genesis - Ado", "First Love - Hikaru Utada"],
    moods: ["melodic", "polished", "emotional", "catchy"],
    eras: ["1990s–present"],
    avoidTerms: ["anime ost", "j-rock"],
    notes: "Beginner-friendly overview. Includes both legacy and modern viral J-pop."
  },
  "mandopop": {
    canonicalGenre: "Mandopop",
    aliases: ["mandarin pop", "chinese pop", "mando pop"],
    seedArtists: ["Jay Chou", "Jolin Tsai", "JJ Lin", "Eason Chan", "G.E.M.", "Eric Chou"],
    relatedArtists: ["Hebe Tien", "Yoga Lin", "Crowd Lu", "A-Mei"],
    starterSongs: ["Simple Love - Jay Chou", "Play - Jolin Tsai", "Those Bygone Years - Hu Xia"],
    moods: ["melodic", "romantic", "nostalgic", "polished"],
    eras: ["1990s–present"],
    avoidTerms: ["c-drama ost"],
  },
  "c-pop": {
    canonicalGenre: "C-Pop",
    aliases: ["cpop", "chinese pop", "c pop"],
    seedArtists: ["Jay Chou", "Jackson Wang", "Lay Zhang", "Lu Han", "Jolin Tsai", "G.E.M."],
    relatedArtists: ["Kris Wu", "JJ Lin", "Eason Chan", "TFBOYS", "Eric Chou"],
    starterSongs: ["Faded - Jackson Wang", "Simple Love - Jay Chou"],
    moods: ["polished", "romantic", "energetic"],
    eras: ["2000s–present"],
    avoidTerms: ["cantopop"],
    notes: "Umbrella for Mandarin and broader Chinese-language pop. Overlaps heavily with mandopop."
  },
  "latin pop": {
    canonicalGenre: "Latin Pop",
    aliases: ["latin", "pop latino", "latin music"],
    seedArtists: ["Shakira", "Enrique Iglesias", "Ricky Martin", "Juanes", "Luis Fonsi", "Rosalía", "Bad Bunny"],
    relatedArtists: ["Maluma", "Ozuna", "Karol G", "Sebastián Yatra", "Camilo"],
    starterSongs: ["Hips Don't Lie - Shakira", "Despacito - Luis Fonsi", "Livin' La Vida Loca - Ricky Martin", "BESO - Rosalía & Rauw Alejandro"],
    moods: ["danceable", "romantic", "festive", "warm"],
    eras: ["1980s–present"],
    avoidTerms: ["latin jazz", "latin house"],
  },
  "reggaeton": {
    canonicalGenre: "Reggaeton",
    aliases: ["regueton", "reggaetón", "perreo"],
    seedArtists: ["Daddy Yankee", "Bad Bunny", "J Balvin", "Ozuna", "Don Omar", "Rauw Alejandro", "Karol G"],
    relatedArtists: ["Farruko", "Sech", "Myke Towers", "Jhayco", "Feid"],
    starterSongs: ["Gasolina - Daddy Yankee", "Tití Me Preguntó - Bad Bunny", "Mi Gente - J Balvin", "Dákiti - Bad Bunny & Jhay Cortez"],
    moods: ["party", "energetic", "sensual", "urban"],
    eras: ["2000s–present"],
    avoidTerms: ["reggae", "dancehall"],
  },
  "afrobeats": {
    canonicalGenre: "Afrobeats",
    aliases: ["afro beats", "afro-beats", "naija pop", "afropop"],
    seedArtists: ["Burna Boy", "Wizkid", "Davido", "Tems", "Rema", "Ayra Starr", "CKay"],
    relatedArtists: ["Fireboy DML", "Omah Lay", "Asake", "Bnxn", "Tiwa Savage"],
    starterSongs: ["Last Last - Burna Boy", "Essence - Wizkid feat. Tems", "Calm Down - Rema", "Love Nwantiti - CKay"],
    moods: ["groovy", "sunny", "danceable", "joyful"],
    eras: ["2010s–present"],
    avoidTerms: ["afro house", "afrobeat"],
    notes: "Modern West African pop. Distinct from Fela Kuti's 'Afrobeat' (no s) and from South African 'Afro House'."
  },
  "amapiano": {
    canonicalGenre: "Amapiano",
    aliases: ["ama piano", "yanos", "piano music south africa"],
    seedArtists: ["Kabza De Small", "DJ Maphorisa", "Focalistic", "Vigro Deep", "De Mthuda", "Uncle Waffles"],
    relatedArtists: ["Young Stunna", "Daliwonga", "DBN Gogo", "Tyler ICU", "Musa Keys"],
    starterSongs: ["Akulaleki - Kabza De Small", "Ke Star - Focalistic", "Tanzania - Uncle Waffles"],
    moods: ["laid-back", "groovy", "percussive", "warm"],
    eras: ["2018–present"],
    avoidTerms: ["piano classical", "piano lessons"],
    notes: "South African genre blending deep house, jazz, and lounge with log drum bass. Global breakout from 2020."
  },
  "dancehall": {
    canonicalGenre: "Dancehall",
    aliases: ["dance hall", "bashment"],
    seedArtists: ["Sean Paul", "Vybz Kartel", "Shaggy", "Popcaan", "Alkaline", "Spice"],
    relatedArtists: ["Skeng", "Masicka", "Shenseea", "Konshens", "Stylo G"],
    starterSongs: ["Get Busy - Sean Paul", "Cheerleader - Omi", "Pon de Floor - Major Lazer"],
    moods: ["party", "energetic", "bass-heavy", "tropical"],
    eras: ["1980s–present"],
    avoidTerms: ["dance music", "dance pop"],
  },
  "indie rock": {
    canonicalGenre: "Indie Rock",
    aliases: ["indie", "alternative indie", "indie guitar"],
    seedArtists: ["Arctic Monkeys", "Tame Impala", "Radiohead", "The Strokes", "Vampire Weekend", "Mac DeMarco", "Bon Iver"],
    relatedArtists: ["Alt-J", "Glass Animals", "Phoebe Bridgers", "Fontaines D.C.", "Alvvays"],
    starterSongs: ["Do I Wanna Know? - Arctic Monkeys", "Sweater Weather - The Neighbourhood", "The Less I Know the Better - Tame Impala", "Last Nite - The Strokes"],
    subgenres: ["garage rock revival", "math rock", "post-rock"],
    moods: ["introspective", "melancholic", "raw", "anthemic"],
    eras: ["1980s–present"],
    avoidTerms: ["indie pop", "indie folk"],
    notes: "Broad beginner entry for guitar-driven independent rock."
  },
  "indie pop": {
    canonicalGenre: "Indie Pop",
    aliases: ["indiepop", "indie synth pop", "twee"],
    seedArtists: ["Alvvays", "Clairo", "beabadoobee", "Japanese Breakfast", "The 1975", "Wallows", "girl in red"],
    relatedArtists: ["Men I Trust", "Snail Mail", "Beach Bunny", "Dayglow", "Still Woozy"],
    starterSongs: ["Archie, Marry Me - Alvvays", "Sofia - Clairo", "Somebody Else - The 1975", "Are You Bored Yet? - Wallows"],
    moods: ["dreamy", "sweet", "nostalgic", "light"],
    eras: ["2010s–present"],
    avoidTerms: ["indie rock"],
  },
  "dream pop": {
    canonicalGenre: "Dream Pop",
    aliases: ["dreampop", "ethereal pop", "atmospheric pop"],
    seedArtists: ["Beach House", "Cocteau Twins", "Mazzy Star", "Cigarettes After Sex", "Slowdive"],
    relatedArtists: ["Wild Nothing", "Warpaint", "Julee Cruise", "DIIV", "Men I Trust"],
    starterSongs: ["Space Song - Beach House", "Fade Into You - Mazzy Star", "Cherry-Coloured Funk - Cocteau Twins", "Apocalypse - Cigarettes After Sex"],
    moods: ["ethereal", "hazy", "melancholic", "intimate"],
    eras: ["1985–present"],
    avoidTerms: ["dream meaning", "sleep music"],
  },
  "shoegaze": {
    canonicalGenre: "Shoegaze",
    aliases: ["shoe gaze", "noise pop", "shoegazer"],
    seedArtists: ["My Bloody Valentine", "Slowdive", "Ride", "Lush", "Swervedriver"],
    relatedArtists: ["Nothing", "DIIV", "Deafheaven", "Ringo Deathstarr", "Whirr"],
    starterSongs: ["Only Shallow - My Bloody Valentine", "Alison - Slowdive", "Vapour Trail - Ride", "When the Sun Hits - Slowdive"],
    moods: ["loud", "dreamy", "wall-of-sound", "immersive"],
    eras: ["1988–1995", "2010s revival"],
    avoidTerms: ["shoe shopping"],
  },
  "post-punk": {
    canonicalGenre: "Post-Punk",
    aliases: ["post punk", "postpunk", "new wave adjacent"],
    seedArtists: ["Joy Division", "Bauhaus", "Siouxsie and the Banshees", "The Cure", "Fontaines D.C.", "Interpol"],
    relatedArtists: ["IDLES", "Shame", "Dry Cleaning", "Squid", "Protomartyr"],
    starterSongs: ["Love Will Tear Us Apart - Joy Division", "Bela Lugosi's Dead - Bauhaus", "Boys Don't Cry - The Cure"],
    moods: ["dark", "angular", "brooding", "literary"],
    eras: ["1978–1985", "2000s revival", "2020s wave"],
    avoidTerms: ["punk rock"],
  },
  "punk": {
    canonicalGenre: "Punk",
    aliases: ["punk rock", "punk music", "classic punk"],
    seedArtists: ["Ramones", "Sex Pistols", "The Clash", "Dead Kennedys", "Bad Religion", "Black Flag"],
    relatedArtists: ["Minor Threat", "Buzzcocks", "Descendents", "Misfits", "NOFX"],
    starterSongs: ["Blitzkrieg Bop - Ramones", "Anarchy in the U.K. - Sex Pistols", "London Calling - The Clash", "Holiday in Cambodia - Dead Kennedys"],
    subgenres: ["hardcore punk", "skate punk", "anarcho-punk"],
    moods: ["raw", "aggressive", "rebellious", "fast"],
    eras: ["1976–present"],
    avoidTerms: ["pop punk", "punk goes pop"],
    notes: "The original punk movement. Fast, stripped-down, confrontational."
  },
  "pop punk": {
    canonicalGenre: "Pop Punk",
    aliases: ["pop-punk", "poppunk", "skate punk pop"],
    seedArtists: ["Blink-182", "Green Day", "Paramore", "Sum 41", "My Chemical Romance", "Fall Out Boy"],
    relatedArtists: ["The Wonder Years", "Neck Deep", "State Champs", "Waterparks", "Stand Atlantic"],
    starterSongs: ["All the Small Things - Blink-182", "Basket Case - Green Day", "Misery Business - Paramore", "Sugar, We're Goin Down - Fall Out Boy"],
    moods: ["energetic", "nostalgic", "angsty", "catchy"],
    eras: ["1994–present"],
    avoidTerms: ["punk", "hardcore"],
  },
  "emo": {
    canonicalGenre: "Emo",
    aliases: ["emo rock", "emo music", "midwest emo", "emo revival"],
    seedArtists: ["American Football", "My Chemical Romance", "Dashboard Confessional", "Jimmy Eat World", "Brand New", "The Promise Ring"],
    relatedArtists: ["Modern Baseball", "Mom Jeans.", "Sunny Day Real Estate", "Cap'n Jazz", "Foxing"],
    starterSongs: ["Never Meant - American Football", "The Middle - Jimmy Eat World", "Helena - My Chemical Romance", "Screaming Infidelities - Dashboard Confessional"],
    moods: ["emotional", "vulnerable", "melodic", "introspective"],
    eras: ["1990s–present"],
    avoidTerms: ["emo trap", "emo rap"],
    notes: "Spans 90s Midwest emo through 2000s mainstream wave and 2010s revival."
  },
  "metal": {
    canonicalGenre: "Metal",
    aliases: ["heavy metal", "metal music"],
    seedArtists: ["Black Sabbath", "Iron Maiden", "Metallica", "Judas Priest", "Slayer", "Megadeth", "Pantera"],
    relatedArtists: ["Tool", "Gojira", "Mastodon", "Lamb of God", "System of a Down"],
    starterSongs: ["Master of Puppets - Metallica", "Iron Man - Black Sabbath", "The Trooper - Iron Maiden", "Raining Blood - Slayer", "Parabola - Tool"],
    subgenres: ["thrash metal", "doom metal", "power metal", "progressive metal", "nu metal"],
    moods: ["aggressive", "powerful", "dark", "epic"],
    eras: ["1970–present"],
    avoidTerms: ["metalcore", "screamo"],
    notes: "Beginner-friendly gateway into metal. Covers classic and essential acts."
  },
  "heavy metal": {
    canonicalGenre: "Heavy Metal",
    aliases: ["classic metal", "traditional metal", "nwobhm"],
    seedArtists: ["Iron Maiden", "Judas Priest", "Black Sabbath", "Dio", "Motorhead", "Accept"],
    relatedArtists: ["Saxon", "Scorpions", "Helloween", "Mercyful Fate", "Manowar"],
    starterSongs: ["The Number of the Beast - Iron Maiden", "Breaking the Law - Judas Priest", "Paranoid - Black Sabbath", "Holy Diver - Dio"],
    moods: ["powerful", "anthemic", "driving", "epic"],
    eras: ["1970–1990"],
    avoidTerms: ["heavy rotation", "heavy bass"],
  },
  "black metal": {
    canonicalGenre: "Black Metal",
    aliases: ["bm", "atmospheric black metal", "raw black metal"],
    seedArtists: ["Mayhem", "Burzum", "Darkthrone", "Emperor", "Bathory", "Immortal"],
    relatedArtists: ["Mgła", "Deafheaven", "Alcest", "Wolves in the Throne Room", "Blut aus Nord"],
    starterSongs: ["Freezing Moon - Mayhem", "Dunkelheit - Burzum", "Transilvanian Hunger - Darkthrone", "I Am the Black Wizards - Emperor"],
    moods: ["cold", "atmospheric", "extreme", "raw"],
    eras: ["1990–present"],
    avoidTerms: ["black music", "black pop"],
  },
  "death metal": {
    canonicalGenre: "Death Metal",
    aliases: ["dm", "brutal death metal", "technical death metal", "tech death"],
    seedArtists: ["Death", "Cannibal Corpse", "Morbid Angel", "Obituary", "Bolt Thrower", "Suffocation"],
    relatedArtists: ["Gorguts", "Nile", "Bloodbath", "Entombed", "Archspire"],
    starterSongs: ["Crystal Mountain - Death", "Hammer Smashed Face - Cannibal Corpse", "Where the Slime Live - Morbid Angel"],
    moods: ["brutal", "intense", "technical", "relentless"],
    eras: ["1987–present"],
    avoidTerms: ["death rock", "deathcore"],
  },
  "metalcore": {
    canonicalGenre: "Metalcore",
    aliases: ["metal core", "melodic metalcore"],
    seedArtists: ["Killswitch Engage", "Parkway Drive", "As I Lay Dying", "August Burns Red", "Architects", "Trivium"],
    relatedArtists: ["Bullet for My Valentine", "Bring Me the Horizon", "The Devil Wears Prada", "Polaris", "Currents"],
    starterSongs: ["My Curse - Killswitch Engage", "Carrion - Parkway Drive", "In Waves - Trivium", "Doomsday - Architects"],
    moods: ["aggressive", "melodic", "anthemic", "intense"],
    eras: ["2000–present"],
    avoidTerms: ["hardcore", "deathcore"],
  },
  "hardcore": {
    canonicalGenre: "Hardcore",
    aliases: ["hardcore punk", "hxc", "beatdown hardcore"],
    seedArtists: ["Black Flag", "Minor Threat", "Bad Brains", "Madball", "Terror", "Turnstile"],
    relatedArtists: ["Knocked Loose", "Code Orange", "Hatebreed", "Gorilla Biscuits", "Have Heart"],
    starterSongs: ["Rise Above - Black Flag", "Straight Edge - Minor Threat", "Mystery - Turnstile", "Banned in D.C. - Bad Brains"],
    moods: ["raw", "intense", "fast", "confrontational"],
    eras: ["1980–present"],
    avoidTerms: ["hardcore techno", "happy hardcore", "hardcore dance"],
  },
  "alt rock": {
    canonicalGenre: "Alternative Rock",
    aliases: ["alternative rock", "alternative", "alt-rock", "alt"],
    seedArtists: ["Radiohead", "Nirvana", "Pixies", "R.E.M.", "The Smashing Pumpkins", "Beck", "Weezer"],
    relatedArtists: ["Foo Fighters", "Cage the Elephant", "The Black Keys", "Queens of the Stone Age", "Modest Mouse"],
    starterSongs: ["Creep - Radiohead", "Smells Like Teen Spirit - Nirvana", "Where Is My Mind? - Pixies", "Loser - Beck", "Bullet with Butterfly Wings - The Smashing Pumpkins"],
    moods: ["introspective", "raw", "melodic", "eclectic"],
    eras: ["1985–present"],
    avoidTerms: ["alt country"],
    notes: "Broad catch-all for guitar rock outside the mainstream. Gateway entry."
  },
  "hip-hop": {
    canonicalGenre: "Hip-Hop",
    aliases: ["hip hop", "hiphop", "rap", "rap music"],
    seedArtists: ["Kendrick Lamar", "Jay-Z", "Nas", "Kanye West", "J. Cole", "Tyler, the Creator", "OutKast", "A Tribe Called Quest"],
    relatedArtists: ["Lil Wayne", "Eminem", "Drake", "Travis Scott", "21 Savage", "JID"],
    starterSongs: ["Alright - Kendrick Lamar", "N.Y. State of Mind - Nas", "Juicy - The Notorious B.I.G.", "Runaway - Kanye West"],
    subgenres: ["boom bap", "trap", "conscious rap", "gangsta rap", "drill"],
    moods: ["confident", "lyrical", "energetic", "introspective"],
    eras: ["1979–present"],
    avoidTerms: ["hip hop workout", "hip hop meditation"],
    notes: "Broad beginner-friendly entry. Spans decades and sub-styles."
  },
  "conscious hip-hop": {
    canonicalGenre: "Conscious Hip-Hop",
    aliases: ["conscious rap", "woke rap", "lyrical hip-hop", "political rap"],
    seedArtists: ["Kendrick Lamar", "Mos Def", "Talib Kweli", "Common", "Lupe Fiasco", "Black Thought"],
    relatedArtists: ["J. Cole", "Noname", "Saba", "Rapsody", "Brother Ali"],
    starterSongs: ["Alright - Kendrick Lamar", "Respiration - Black Star", "I Used to Love H.E.R. - Common", "Be - Common"],
    moods: ["thoughtful", "lyrical", "political", "introspective"],
    eras: ["1988–present"],
    avoidTerms: ["mumble rap"],
  },
  "jazz rap": {
    canonicalGenre: "Jazz Rap",
    aliases: ["jazz hip-hop", "jazz-rap", "jazzy hip hop"],
    seedArtists: ["A Tribe Called Quest", "Guru", "Digable Planets", "The Roots", "Robert Glasper", "Kendrick Lamar"],
    relatedArtists: ["Anderson .Paak", "Noname", "Terrace Martin", "Madlib", "Kamasi Washington"],
    starterSongs: ["Electric Relaxation - A Tribe Called Quest", "Rebirth of Slick (Cool Like Dat) - Digable Planets", "Doo Wop (That Thing) - Lauryn Hill"],
    moods: ["smooth", "cerebral", "laid-back", "sophisticated"],
    eras: ["1991–present"],
    avoidTerms: ["smooth jazz", "jazz fusion"],
  },
  "trap": {
    canonicalGenre: "Trap",
    aliases: ["trap music", "trap rap", "atlanta trap"],
    seedArtists: ["Future", "Young Thug", "Travis Scott", "Migos", "Gucci Mane", "21 Savage", "Metro Boomin"],
    relatedArtists: ["Gunna", "Lil Baby", "Playboi Carti", "Don Toliver", "Yeat"],
    starterSongs: ["Mask Off - Future", "goosebumps - Travis Scott", "Bad and Boujee - Migos", "a]lot - 21 Savage"],
    moods: ["hard", "atmospheric", "dark", "bass-heavy"],
    eras: ["2010–present"],
    avoidTerms: ["trap workout", "trap yoga", "edm trap"],
  },
  "boom bap": {
    canonicalGenre: "Boom Bap",
    aliases: ["boom-bap", "golden age hip-hop", "90s hip hop", "east coast hip hop"],
    seedArtists: ["Nas", "The Notorious B.I.G.", "Wu-Tang Clan", "DJ Premier", "Pete Rock", "MF DOOM", "A Tribe Called Quest"],
    relatedArtists: ["Joey Bada$$", "Griselda", "Roc Marciano", "Statik Selektah", "Boldy James"],
    starterSongs: ["N.Y. State of Mind - Nas", "C.R.E.A.M. - Wu-Tang Clan", "Juicy - The Notorious B.I.G.", "Accordion - Madvillain"],
    moods: ["raw", "lyrical", "gritty", "nostalgic"],
    eras: ["1986–1997", "ongoing revival"],
    avoidTerms: ["lo-fi beats"],
  },
  "r&b": {
    canonicalGenre: "R&B",
    aliases: ["rnb", "r and b", "rhythm and blues", "contemporary r&b"],
    seedArtists: ["SZA", "Frank Ocean", "The Weeknd", "Daniel Caesar", "H.E.R.", "Beyoncé", "Usher"],
    relatedArtists: ["Summer Walker", "Brent Faiyaz", "Jorja Smith", "Kehlani", "Jhené Aiko"],
    starterSongs: ["Kill Bill - SZA", "Blinding Lights - The Weeknd", "Thinking About You - Frank Ocean", "Best Part - Daniel Caesar"],
    subgenres: ["neo-soul", "alternative r&b", "quiet storm"],
    moods: ["smooth", "emotional", "sensual", "intimate"],
    eras: ["1980s–present"],
    avoidTerms: ["r&b workout"],
    notes: "Modern R&B entry. Beginner-friendly across mainstream and alternative styles."
  },
  "neo-soul": {
    canonicalGenre: "Neo-Soul",
    aliases: ["neo soul", "neosoul", "nu soul"],
    seedArtists: ["Erykah Badu", "D'Angelo", "Lauryn Hill", "Jill Scott", "Maxwell", "Musiq Soulchild"],
    relatedArtists: ["Anderson .Paak", "Hiatus Kaiyote", "Solange", "Lianne La Havas", "Snoh Aalegra"],
    starterSongs: ["Bag Lady - Erykah Badu", "Untitled (How Does It Feel) - D'Angelo", "Ex-Factor - Lauryn Hill", "Golden - Jill Scott"],
    moods: ["warm", "organic", "spiritual", "groovy"],
    eras: ["1994–present"],
    avoidTerms: ["soul food", "soul music"],
  },
  "soul": {
    canonicalGenre: "Soul",
    aliases: ["soul music", "classic soul", "60s soul", "70s soul"],
    seedArtists: ["Aretha Franklin", "Marvin Gaye", "Otis Redding", "Stevie Wonder", "Al Green", "Sam Cooke"],
    relatedArtists: ["Curtis Mayfield", "Bill Withers", "Nina Simone", "Ray Charles", "Donny Hathaway"],
    starterSongs: ["Respect - Aretha Franklin", "What's Going On - Marvin Gaye", "A Change Is Gonna Come - Sam Cooke", "Let's Stay Together - Al Green"],
    moods: ["warm", "passionate", "heartfelt", "timeless"],
    eras: ["1960s–1970s"],
    avoidTerms: ["soul food", "soulful house"],
    notes: "Classic soul canon. For modern soul, see 'neo-soul'."
  },
  "funk": {
    canonicalGenre: "Funk",
    aliases: ["funk music", "classic funk", "p-funk"],
    seedArtists: ["James Brown", "Parliament", "Funkadelic", "Sly and the Family Stone", "Earth, Wind & Fire", "Prince"],
    relatedArtists: ["Bootsy Collins", "The Meters", "Tower of Power", "Vulfpeck", "Lettuce"],
    starterSongs: ["Get Up (I Feel Like Being a) Sex Machine - James Brown", "Give Up the Funk - Parliament", "September - Earth, Wind & Fire"],
    moods: ["groovy", "danceable", "energetic", "playful"],
    eras: ["1965–present"],
    avoidTerms: ["funk house", "funky house"],
  },
  "jazz": {
    canonicalGenre: "Jazz",
    aliases: ["jazz music", "jazz standards"],
    seedArtists: ["Miles Davis", "John Coltrane", "Thelonious Monk", "Charlie Parker", "Duke Ellington", "Bill Evans", "Kamasi Washington"],
    relatedArtists: ["Herbie Hancock", "Chet Baker", "Sonny Rollins", "Esperanza Spalding", "Robert Glasper"],
    starterSongs: ["So What - Miles Davis", "Take Five - Dave Brubeck", "A Love Supreme, Pt. 1: Acknowledgement - John Coltrane", "'Round Midnight - Thelonious Monk"],
    subgenres: ["bebop", "cool jazz", "modal jazz", "hard bop", "free jazz", "fusion"],
    moods: ["sophisticated", "improvisational", "mellow", "complex"],
    eras: ["1920s–present"],
    avoidTerms: ["jazz workout", "smooth jazz", "jazzy beats"],
    notes: "Broad beginner entry into jazz. Includes both classic and modern artists."
  },
  "bebop": {
    canonicalGenre: "Bebop",
    aliases: ["bop", "be-bop"],
    seedArtists: ["Charlie Parker", "Dizzy Gillespie", "Thelonious Monk", "Bud Powell", "Max Roach"],
    relatedArtists: ["Dexter Gordon", "Sonny Stitt", "Art Blakey", "Clifford Brown", "Fats Navarro"],
    starterSongs: ["Ornithology - Charlie Parker", "A Night in Tunisia - Dizzy Gillespie", "Blue Monk - Thelonious Monk"],
    moods: ["virtuosic", "fast", "complex", "improvisational"],
    eras: ["1940s–1950s"],
    avoidTerms: ["be bop a lula"],
  },
  "modal jazz": {
    canonicalGenre: "Modal Jazz",
    aliases: ["modal", "post-bop modal"],
    seedArtists: ["Miles Davis", "John Coltrane", "Bill Evans", "McCoy Tyner", "Herbie Hancock"],
    relatedArtists: ["Wayne Shorter", "Joe Henderson", "Art Pepper", "Eric Dolphy"],
    starterSongs: ["So What - Miles Davis", "Impressions - John Coltrane", "Maiden Voyage - Herbie Hancock", "Blue in Green - Miles Davis"],
    moods: ["spacious", "meditative", "exploratory", "cool"],
    eras: ["1958–1970s"],
    avoidTerms: ["modal music theory"],
  },
  "bossa nova": {
    canonicalGenre: "Bossa Nova",
    aliases: ["bossa", "brazilian jazz", "bossa nova jazz"],
    seedArtists: ["Antônio Carlos Jobim", "João Gilberto", "Stan Getz", "Astrud Gilberto", "Sérgio Mendes"],
    relatedArtists: ["Elis Regina", "Caetano Veloso", "Gal Costa", "Gilberto Gil", "Marcos Valle"],
    starterSongs: ["The Girl from Ipanema - Stan Getz & João Gilberto", "Corcovado - Antônio Carlos Jobim", "Águas de Março - Antônio Carlos Jobim"],
    moods: ["breezy", "romantic", "gentle", "warm"],
    eras: ["1958–present"],
    avoidTerms: ["bossa nova workout"],
  },
  "ambient": {
    canonicalGenre: "Ambient",
    aliases: ["ambient music", "atmospheric", "ambient electronic"],
    seedArtists: ["Brian Eno", "Aphex Twin", "Stars of the Lid", "Tim Hecker", "Nils Frahm"],
    relatedArtists: ["Grouper", "Gas", "William Basinski", "Boards of Canada", "Ólafur Arnalds"],
    starterSongs: ["Music for Airports 1/1 - Brian Eno", "Xtal - Aphex Twin", "An Ending (Ascent) - Brian Eno"],
    subgenres: ["dark ambient", "ambient drone", "space ambient"],
    moods: ["meditative", "spacious", "calm", "immersive"],
    eras: ["1978–present"],
    avoidTerms: ["ambient noise", "white noise", "sleep sounds"],
  },
  "downtempo": {
    canonicalGenre: "Downtempo",
    aliases: ["downbeat", "chillout electronic"],
    seedArtists: ["Bonobo", "Thievery Corporation", "Tycho", "Emancipator", "Nightmares on Wax"],
    relatedArtists: ["Little People", "Maribou State", "Catching Flies", "Frameworks", "Kiasmos"],
    starterSongs: ["Kerala - Bonobo", "A Walk - Tycho", "Lebanese Blonde - Thievery Corporation", "First Snow - Emancipator"],
    moods: ["relaxed", "warm", "meditative", "textured"],
    eras: ["1993–present"],
    avoidTerms: ["downtempo yoga"],
  },
  "trip-hop": {
    canonicalGenre: "Trip-Hop",
    aliases: ["trip hop", "triphop", "bristol sound"],
    seedArtists: ["Massive Attack", "Portishead", "Tricky", "Morcheeba", "UNKLE"],
    relatedArtists: ["Sneaker Pimps", "Hooverphonic", "Lamb", "Archive", "Wax Tailor"],
    starterSongs: ["Teardrop - Massive Attack", "Glory Box - Portishead", "Hell Is Round the Corner - Tricky", "Angel - Massive Attack"],
    moods: ["dark", "cinematic", "moody", "nocturnal"],
    eras: ["1991–2000", "ongoing influence"],
    avoidTerms: ["hip hop trip"],
  },
  "chillout": {
    canonicalGenre: "Chillout",
    aliases: ["chill out", "chill", "chill electronic", "lounge"],
    seedArtists: ["Zero 7", "Air", "Groove Armada", "Café del Mar artists", "Lemon Jelly"],
    relatedArtists: ["Thievery Corporation", "Morcheeba", "Röyksopp", "Goldfrapp", "Moby"],
    starterSongs: ["Destiny - Zero 7", "Cherry Blossom Girl - Air", "At the River - Groove Armada", "Porcelain - Moby"],
    moods: ["relaxed", "dreamy", "smooth", "sunset"],
    eras: ["1998–present"],
    avoidTerms: ["chill workout", "chill beats study"],
  },
  "lo-fi beats": {
    canonicalGenre: "Lo-Fi Beats",
    aliases: ["lo-fi hip hop", "lofi", "lo fi", "lofi beats", "chillhop", "study beats"],
    seedArtists: ["Nujabes", "J Dilla", "Tomppabeats", "Jinsang", "Idealism", "Quickly, Quickly"],
    relatedArtists: ["Kupla", "Philanthrope", "In Love with a Ghost", "Moow", "Wun Two"],
    starterSongs: ["Aruarian Dance - Nujabes", "So.Far - Tomppabeats", "Donuts (Intro) - J Dilla"],
    moods: ["chill", "nostalgic", "mellow", "studious"],
    eras: ["2010s–present"],
    avoidTerms: ["lo-fi house", "lo-fi rock"],
    notes: "Beat-driven instrumental hip-hop for study and relaxation. Rooted in Nujabes and J Dilla production."
  },
  "piano": {
    canonicalGenre: "Piano",
    aliases: ["piano music", "solo piano", "modern piano", "piano instrumental"],
    seedArtists: ["Nils Frahm", "Ólafur Arnalds", "Yiruma", "Ludovico Einaudi", "Chilly Gonzales"],
    relatedArtists: ["Agnes Obel", "Joep Beving", "Dustin O'Halloran", "Chad Lawson", "Hania Rani"],
    starterSongs: ["Says - Nils Frahm", "River Flows in You - Yiruma", "Nuvole Bianche - Ludovico Einaudi", "Near Light - Ólafur Arnalds"],
    moods: ["contemplative", "gentle", "intimate", "cinematic"],
    eras: ["2000s–present"],
    avoidTerms: ["piano tutorial", "piano lesson", "piano practice"],
    notes: "Modern neoclassical and solo piano. For classical piano, see 'classical essentials'."
  },
  "classical essentials": {
    canonicalGenre: "Classical Essentials",
    aliases: ["classical", "classical music", "orchestral", "classical starter"],
    seedArtists: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frédéric Chopin", "Claude Debussy", "Pyotr Ilyich Tchaikovsky"],
    relatedArtists: ["Sergei Rachmaninoff", "Johannes Brahms", "Antonio Vivaldi", "Gustav Mahler", "Dmitri Shostakovich"],
    starterSongs: ["Clair de Lune - Claude Debussy", "Moonlight Sonata - Ludwig van Beethoven", "Four Seasons: Spring - Antonio Vivaldi", "Nocturne Op. 9 No. 2 - Frédéric Chopin"],
    subgenres: ["baroque", "romantic", "impressionist", "contemporary classical"],
    moods: ["grand", "contemplative", "dramatic", "serene"],
    eras: ["1600–present"],
    avoidTerms: ["classical conditioning", "classical guitar"],
    notes: "Beginner-friendly classical gateway. Representative composers across eras."
  },
  "film scores": {
    canonicalGenre: "Film Scores",
    aliases: ["soundtrack", "movie music", "ost", "film music", "cinematic music"],
    seedArtists: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore", "Thomas Newman", "Alexandre Desplat"],
    relatedArtists: ["Ludwig Göransson", "Jonny Greenwood", "Michael Giacchino", "Joe Hisaishi", "Trent Reznor"],
    starterSongs: ["Time - Hans Zimmer", "Hedwig's Theme - John Williams", "The Ecstasy of Gold - Ennio Morricone", "Merry Christmas Mr. Lawrence - Ryuichi Sakamoto"],
    moods: ["cinematic", "epic", "emotional", "dramatic"],
    eras: ["1960s–present"],
    avoidTerms: ["movie trailer music", "epic music mix"],
  },
  "acid house": {
    canonicalGenre: "Acid House",
    aliases: ["acid", "acid techno"],
    seedArtists: ["Phuture", "808 State", "A Guy Called Gerald", "Hardfloor", "DJ Pierre"],
    relatedArtists: ["Ceephax Acid Crew", "Luke Vibert", "Plastikman", "AFX"],
    starterSongs: ["Acid Tracks - Phuture", "Pacific State - 808 State", "Voodoo Ray - A Guy Called Gerald"],
    moods: ["squelchy", "hypnotic", "raw", "psychedelic"],
    eras: ["1986–present"],
    avoidTerms: ["acid rock", "acid jazz"],
    notes: "Built around the Roland TB-303 bass synthesizer. Foundation of rave culture."
  },
  "tech house": {
    canonicalGenre: "Tech House",
    aliases: ["techhouse", "tech-house", "minimal tech house"],
    seedArtists: ["Fisher", "Chris Lake", "Green Velvet", "Patrick Topping", "Jamie Jones", "Solardo"],
    relatedArtists: ["Michael Bibi", "Eli Brown", "PAWSA", "Dennis Cruz", "Detlef"],
    starterSongs: ["Losing It - Fisher", "Turning Me Up - BLR", "La La Land - Green Velvet"],
    moods: ["groovy", "driving", "playful", "dancefloor"],
    eras: ["2000–present"],
    avoidTerms: ["tech startup"],
  },
  "nu disco": {
    canonicalGenre: "Nu Disco",
    aliases: ["nu-disco", "new disco", "indie disco", "cosmic disco"],
    seedArtists: ["Todd Terje", "Lindstrøm", "Röyksopp", "Breakbot", "Escort"],
    relatedArtists: ["Prins Thomas", "In Flagranti", "Aeroplane", "Tensnake", "Purple Disco Machine"],
    starterSongs: ["Inspector Norse - Todd Terje", "Baby I'm Yours - Breakbot", "Delorean Dynamite - Todd Terje"],
    moods: ["funky", "retro", "uplifting", "groovy"],
    eras: ["2006–present"],
    avoidTerms: ["70s disco"],
  },
  "electro": {
    canonicalGenre: "Electro",
    aliases: ["electro music", "electro funk", "electro hip-hop"],
    seedArtists: ["Kraftwerk", "Afrika Bambaataa", "Egyptian Lover", "Cybotron", "Drexciya"],
    relatedArtists: ["DJ Stingray", "Helena Hauff", "Dopplereffekt", "DMX Krew", "The Hacker"],
    starterSongs: ["Planet Rock - Afrika Bambaataa", "Clear - Cybotron", "Trans-Europe Express - Kraftwerk"],
    moods: ["robotic", "futuristic", "raw", "mechanical"],
    eras: ["1982–present"],
    avoidTerms: ["electro house", "electro pop", "EDM"],
    notes: "Original electro: robotic funk built on the TR-808. Not to be confused with electro house or EDM."
  },
  "dub techno": {
    canonicalGenre: "Dub Techno",
    aliases: ["dub-techno", "deep dub"],
    seedArtists: ["Basic Channel", "Rhythm & Sound", "Vladislav Delay", "Deepchord", "Fluxion"],
    relatedArtists: ["cv313", "Porter Ricks", "Echospace", "Vril", "Svreca"],
    starterSongs: ["Phylyps Trak - Basic Channel", "Ultraviolet - Deepchord", "Carrier - Fluxion"],
    moods: ["hypnotic", "meditative", "oceanic", "spacious"],
    eras: ["1993–present"],
    avoidTerms: ["dub reggae", "dubstep"],
  },
  "psytrance": {
    canonicalGenre: "Psytrance",
    aliases: ["psychedelic trance", "psy", "goa trance", "full on"],
    seedArtists: ["Infected Mushroom", "Astrix", "Vini Vici", "Shpongle", "Hallucinogen"],
    relatedArtists: ["Ace Ventura", "Captain Hook", "Neelix", "Yahel", "1200 Micrograms"],
    starterSongs: ["Becoming Insane - Infected Mushroom", "He.Art - Vini Vici", "Type 1 - Astrix", "Divine Moments of Truth - Shpongle"],
    moods: ["psychedelic", "driving", "hypnotic", "transcendent"],
    eras: ["1995–present"],
    avoidTerms: ["psychedelic rock"],
  },
  "dubstep": {
    canonicalGenre: "Dubstep",
    aliases: ["dubstep music", "uk dubstep", "bass music"],
    seedArtists: ["Skream", "Burial", "Digital Mystikz", "Rusko", "Excision", "Skrillex"],
    relatedArtists: ["Zomboy", "Subfocus", "Caspa", "Hatcha", "MUST DIE!"],
    starterSongs: ["Midnight Request Line - Skream", "Archangel - Burial", "Scary Monsters and Nice Sprites - Skrillex"],
    subgenres: ["deep dubstep", "brostep", "riddim"],
    moods: ["dark", "heavy", "bass-driven", "intense"],
    eras: ["2004–present"],
    avoidTerms: ["dub reggae", "dubstep remix"],
    notes: "Spans original UK deep dubstep and the heavier North American 'brostep' wave."
  },
  "synthwave": {
    canonicalGenre: "Synthwave",
    aliases: ["retrowave", "outrun", "synthwave music", "80s synth"],
    seedArtists: ["Kavinsky", "Perturbator", "Carpenter Brut", "Com Truise", "Gunship"],
    relatedArtists: ["Timecop1983", "FM-84", "The Midnight", "Lazerhawk", "Dance with the Dead"],
    starterSongs: ["Nightcall - Kavinsky", "Turbo Killer - Carpenter Brut", "Tech Noir - Gunship"],
    moods: ["retro", "cinematic", "dark", "nostalgic"],
    eras: ["2008–present"],
    avoidTerms: ["synth pop", "80s pop"],
    notes: "Modern electronic music evoking 80s sci-fi and action film aesthetics."
  },
  "uk drill": {
    canonicalGenre: "UK Drill",
    aliases: ["drill uk", "british drill"],
    seedArtists: ["Central Cee", "Headie One", "Digga D", "Tion Wayne", "M1llionz", "Russ Millions"],
    relatedArtists: ["K-Trap", "Unknown T", "Fivio Foreign", "Pop Smoke", "Knucks"],
    starterSongs: ["Doja - Central Cee", "Edna Medley - Headie One", "Body - Tion Wayne & Russ Millions"],
    moods: ["hard", "dark", "rhythmic", "street"],
    eras: ["2017–present"],
    avoidTerms: ["power drill", "drill music USA"],
  },
  "grime": {
    canonicalGenre: "Grime",
    aliases: ["grime music", "uk grime"],
    seedArtists: ["Skepta", "Wiley", "Stormzy", "Dizzee Rascal", "JME", "Kano"],
    relatedArtists: ["Novelist", "D Double E", "P Money", "Chip", "Ghetts"],
    starterSongs: ["Shutdown - Skepta", "Bonkers - Dizzee Rascal", "That's Not Me - Skepta", "Blinded by Your Grace, Pt. 2 - Stormzy"],
    moods: ["aggressive", "raw", "energetic", "urban"],
    eras: ["2002–present"],
    avoidTerms: ["grime cleaning"],
  },
  "afro soul": {
    canonicalGenre: "Afro Soul",
    aliases: ["african soul", "afrosoul"],
    seedArtists: ["Tems", "Asa", "Sade", "Ayo", "Fatoumata Diawara"],
    relatedArtists: ["Omah Lay", "Tiwa Savage", "Jorja Smith", "Lianne La Havas"],
    starterSongs: ["Free Mind - Tems", "Jailer - Asa", "No Ordinary Love - Sade"],
    moods: ["soulful", "warm", "smooth", "emotional"],
    eras: ["2000s–present"],
    avoidTerms: ["afro house", "afrobeats"],
  },
  "alternative r&b": {
    canonicalGenre: "Alternative R&B",
    aliases: ["alt r&b", "alt rnb", "pbr&b", "dark r&b"],
    seedArtists: ["Frank Ocean", "The Weeknd", "FKA twigs", "SZA", "Blood Orange", "Kelela"],
    relatedArtists: ["Sampha", "James Blake", "Daniel Caesar", "Brent Faiyaz", "Steve Lacy"],
    starterSongs: ["Thinkin Bout You - Frank Ocean", "The Hills - The Weeknd", "Cellophane - FKA twigs", "Good Days - SZA"],
    moods: ["moody", "atmospheric", "intimate", "experimental"],
    eras: ["2011–present"],
    avoidTerms: ["classic r&b"],
  },
  "gospel": {
    canonicalGenre: "Gospel",
    aliases: ["gospel music", "contemporary gospel", "christian soul"],
    seedArtists: ["Kirk Franklin", "Mahalia Jackson", "Fred Hammond", "Tye Tribbett", "CeCe Winans"],
    relatedArtists: ["Maverick City Music", "Elevation Worship", "Jonathan McReynolds", "Todd Dulaney", "Tamela Mann"],
    starterSongs: ["Stomp - Kirk Franklin", "Total Praise - Richard Smallwood", "Optimistic - Sounds of Blackness"],
    moods: ["uplifting", "spiritual", "joyful", "powerful"],
    eras: ["1930s–present"],
    avoidTerms: ["gospel house", "gospel techno"],
  },
  "blues": {
    canonicalGenre: "Blues",
    aliases: ["blues music", "electric blues", "delta blues"],
    seedArtists: ["B.B. King", "Muddy Waters", "Robert Johnson", "Howlin' Wolf", "John Lee Hooker", "Buddy Guy"],
    relatedArtists: ["Stevie Ray Vaughan", "Gary Clark Jr.", "Joe Bonamassa", "Taj Mahal", "Keb' Mo'"],
    starterSongs: ["The Thrill Is Gone - B.B. King", "Hoochie Coochie Man - Muddy Waters", "Boom Boom - John Lee Hooker"],
    subgenres: ["delta blues", "chicago blues", "electric blues", "blues rock"],
    moods: ["raw", "soulful", "gritty", "emotional"],
    eras: ["1920s–present"],
    avoidTerms: ["feeling blue", "blues clues"],
    notes: "Beginner-friendly overview of American blues tradition."
  },
  "reggae": {
    canonicalGenre: "Reggae",
    aliases: ["reggae music", "roots reggae", "dub"],
    seedArtists: ["Bob Marley", "Peter Tosh", "Jimmy Cliff", "Burning Spear", "Lee Scratch Perry", "Toots and the Maytals"],
    relatedArtists: ["Steel Pulse", "Dennis Brown", "Gregory Isaacs", "Chronixx", "Protoje"],
    starterSongs: ["No Woman, No Cry - Bob Marley", "The Harder They Come - Jimmy Cliff", "Many Rivers to Cross - Jimmy Cliff"],
    subgenres: ["roots reggae", "dub", "lovers rock", "ska"],
    moods: ["laid-back", "conscious", "spiritual", "warm"],
    eras: ["1960s–present"],
    avoidTerms: ["reggaeton"],
  },
  "country": {
    canonicalGenre: "Country",
    aliases: ["country music", "modern country", "country western"],
    seedArtists: ["Johnny Cash", "Dolly Parton", "Willie Nelson", "Chris Stapleton", "Zach Bryan", "Kacey Musgraves"],
    relatedArtists: ["Tyler Childers", "Sturgill Simpson", "Morgan Wallen", "Luke Combs", "Charley Crockett"],
    starterSongs: ["Ring of Fire - Johnny Cash", "Jolene - Dolly Parton", "Tennessee Whiskey - Chris Stapleton", "Something in the Orange - Zach Bryan"],
    subgenres: ["outlaw country", "bro country", "americana", "alt country"],
    moods: ["storytelling", "heartfelt", "nostalgic", "rootsy"],
    eras: ["1920s–present"],
    avoidTerms: ["country house", "country pop"],
    notes: "Broad gateway from classic to modern country."
  },
  "folk": {
    canonicalGenre: "Folk",
    aliases: ["folk music", "indie folk", "acoustic folk"],
    seedArtists: ["Bob Dylan", "Joni Mitchell", "Bon Iver", "Fleet Foxes", "Iron & Wine", "Nick Drake"],
    relatedArtists: ["Phoebe Bridgers", "Big Thief", "Sufjan Stevens", "Elliott Smith", "The Tallest Man on Earth"],
    starterSongs: ["Blowin' in the Wind - Bob Dylan", "Big Yellow Taxi - Joni Mitchell", "Skinny Love - Bon Iver", "White Winter Hymnal - Fleet Foxes"],
    moods: ["intimate", "acoustic", "poetic", "warm"],
    eras: ["1960s–present"],
    avoidTerms: ["folk dance", "folklore taylor"],
  },
  "new wave": {
    canonicalGenre: "New Wave",
    aliases: ["new wave music", "synth pop", "80s new wave"],
    seedArtists: ["Depeche Mode", "New Order", "Talking Heads", "The Smiths", "Tears for Fears", "Duran Duran"],
    relatedArtists: ["OMD", "Gary Numan", "Blondie", "Echo & the Bunnymen", "A Flock of Seagulls"],
    starterSongs: ["Enjoy the Silence - Depeche Mode", "Blue Monday - New Order", "Psycho Killer - Talking Heads", "Everybody Wants to Rule the World - Tears for Fears"],
    moods: ["angular", "atmospheric", "danceable", "moody"],
    eras: ["1978–1986"],
    avoidTerms: ["new wave french cinema"],
  },
  "grunge": {
    canonicalGenre: "Grunge",
    aliases: ["grunge rock", "seattle sound", "90s grunge"],
    seedArtists: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains", "Mudhoney"],
    relatedArtists: ["Stone Temple Pilots", "Screaming Trees", "Hole", "Melvins", "Temple of the Dog"],
    starterSongs: ["Smells Like Teen Spirit - Nirvana", "Black Hole Sun - Soundgarden", "Alive - Pearl Jam", "Rooster - Alice in Chains"],
    moods: ["raw", "angsty", "heavy", "melancholic"],
    eras: ["1988–1997"],
    avoidTerms: ["grunge aesthetic"],
  },
  "world music": {
    canonicalGenre: "World Music",
    aliases: ["global music", "world fusion"],
    seedArtists: ["Fela Kuti", "Ali Farka Touré", "Tinariwen", "Khruangbin", "Youssou N'Dour", "Oumou Sangaré"],
    relatedArtists: ["Bombino", "Mdou Moctar", "Rokia Traoré", "Angelique Kidjo", "Baba Maal"],
    starterSongs: ["Zombie - Fela Kuti", "Savane - Ali Farka Touré", "Maria Tambien - Khruangbin"],
    moods: ["diverse", "rhythmic", "soulful", "expansive"],
    eras: ["1960s–present"],
    avoidTerms: ["world news"],
    notes: "Broad entry. Best paired with more specific regional genres."
  },
  "hard bop": {
    canonicalGenre: "Hard Bop",
    aliases: ["hardbop"],
    seedArtists: ["Art Blakey", "Horace Silver", "Clifford Brown", "Lee Morgan", "Cannonball Adderley"],
    relatedArtists: ["Freddie Hubbard", "Hank Mobley", "Dexter Gordon", "Bobby Hutcherson", "Kenny Dorham"],
    starterSongs: ["Moanin' - Art Blakey and the Jazz Messengers", "The Sidewinder - Lee Morgan", "Song for My Father - Horace Silver"],
    moods: ["soulful", "driving", "bluesy", "swinging"],
    eras: ["1955–1970"],
    avoidTerms: ["hard rock", "hard dance"],
  },
  "jazz fusion": {
    canonicalGenre: "Jazz Fusion",
    aliases: ["fusion", "jazz rock", "jazz-funk fusion"],
    seedArtists: ["Herbie Hancock", "Weather Report", "Return to Forever", "Mahavishnu Orchestra", "Miles Davis"],
    relatedArtists: ["Pat Metheny", "Snarky Puppy", "Chick Corea", "John McLaughlin", "Stanley Clarke"],
    starterSongs: ["Chameleon - Herbie Hancock", "Birdland - Weather Report", "Bitches Brew - Miles Davis"],
    moods: ["virtuosic", "groovy", "experimental", "complex"],
    eras: ["1969–present"],
    avoidTerms: ["fusion cuisine", "nuclear fusion"],
  },
};
