export type SeedGenreEntry = {
  canonicalGenre: string;
  aliases: string[];
  seedArtists: string[];
  relatedArtists: string[];
  starterSongs?: string[];
  subgenres?: string[];
  moods?: string[];
  eras?: string[];
  avoidTerms?: string[];
  notes?: string;
};

export const GENRE_SEED_MAP: Record<string, SeedGenreEntry> = {
  "tropical house": {
    canonicalGenre: "tropical house",
    aliases: ["tropical", "sunny house", "beach house edm"],
    seedArtists: ["Kygo", "Klingande", "Bakermat", "Sam Feldt", "Lost Frequencies", "Jubel"],
    relatedArtists: ["Felix Jaehn", "Thomas Jack", "Robin Schulz", "Matoma", "Nora En Pure"],
    starterSongs: ["Firestone", "Jubel", "Show Me Love", "Are You With Me"],
    subgenres: ["deep house", "melodic house"],
    moods: ["warm", "summery", "uplifting", "melodic"],
    eras: ["2010s", "2020s"],
    avoidTerms: ["tropical house", "best of tropical house", "workout mix"],
  },
  "deep house": {
    canonicalGenre: "deep house",
    aliases: ["deeper house", "deep club"],
    seedArtists: ["Nora En Pure", "Duke Dumont", "Ben Böhmer", "Lane 8", "Gorgon City", "MK"],
    relatedArtists: ["Claptone", "Elderbrook", "Yotto", "CamelPhat", "Solomun"],
    starterSongs: ["Ocean Drive", "Cola", "Glue", "The Age of Love"],
    subgenres: ["melodic house", "house"],
    moods: ["smooth", "groovy", "night drive", "atmospheric"],
    avoidTerms: ["deep house", "deep house mix"],
  },
  "soulful house": {
    canonicalGenre: "soulful house",
    aliases: ["soulful deep house", "vocal house", "gospel house"],
    seedArtists: ["Kerri Chandler", "Louie Vega", "Atjazz", "DJ Spen", "Saison", "Opolopo"],
    relatedArtists: ["Dennis Ferrer", "Masters At Work", "Miguel Migs", "Osunlade", "Crackazat"],
    starterSongs: ["Atmosphere", "Bar A Thym", "Falling Up"],
    subgenres: ["house", "deep house", "garage house"],
    moods: ["warm", "uplifting", "groovy", "vocal"],
    avoidTerms: ["soulful house mix"],
  },
  "jazzy house": {
    canonicalGenre: "jazzy house",
    aliases: ["jazz house", "jazz-infused house"],
    seedArtists: ["Folamour", "Crackazat", "Cody Currie", "Bellaire", "Demuja", "Session Victim"],
    relatedArtists: ["Jitwam", "Tour-Maubourg", "DJOKO", "Moods", "Kerri Chandler"],
    starterSongs: ["Devoted To U", "What U Need", "La Complainte de la Butte"],
    subgenres: ["house", "soulful house", "disco house"],
    moods: ["jazzy", "groovy", "sunny", "musicianship"],
    avoidTerms: ["jazz house mix"],
  },
  "melodic house": {
    canonicalGenre: "melodic house",
    aliases: ["organic melodic house", "emotive house"],
    seedArtists: ["Ben Böhmer", "Lane 8", "Yotto", "Marsh", "Nils Hoffmann", "Sultan + Shepard"],
    relatedArtists: ["Tinlicker", "RÜFÜS DU SOL", "Nora En Pure", "Monolink", "ODESZA"],
    subgenres: ["deep house", "progressive house"],
    moods: ["emotional", "atmospheric", "euphoric"],
    avoidTerms: ["melodic house mix"],
  },
  house: {
    canonicalGenre: "house",
    aliases: ["house music"],
    seedArtists: ["Frankie Knuckles", "Marshall Jefferson", "Kerri Chandler", "MK", "Todd Terry", "Purple Disco Machine"],
    relatedArtists: ["Masters At Work", "Peggy Gou", "Disclosure", "Honey Dijon", "Duke Dumont"],
    subgenres: ["deep house", "soulful house", "garage house", "disco house"],
    moods: ["dancefloor", "groovy", "uplifting"],
    avoidTerms: ["house music dj", "house mix"],
  },
  techno: {
    canonicalGenre: "techno",
    aliases: ["club techno"],
    seedArtists: ["Charlotte de Witte", "Amelie Lens", "Jeff Mills", "Carl Craig", "Adam Beyer", "Richie Hawtin"],
    relatedArtists: ["Ben Klock", "Sven Väth", "Chris Liebing", "ARTBAT", "ANNA"],
    subgenres: ["melodic techno", "minimal techno"],
    moods: ["driving", "hypnotic", "dark"],
    avoidTerms: ["techno mix", "hard techno workout"],
  },
  "melodic techno": {
    canonicalGenre: "melodic techno",
    aliases: ["melodic club", "afterlife style"],
    seedArtists: ["Tale Of Us", "ARTBAT", "Anyma", "Adriatique", "Mathame", "Stephan Bodzin"],
    relatedArtists: ["Kevin de Vries", "Mind Against", "Agents Of Time", "Massano", "Colyn"],
    subgenres: ["techno", "melodic house"],
    moods: ["cinematic", "driving", "euphoric"],
    avoidTerms: ["melodic techno mix"],
  },
  disco: {
    canonicalGenre: "disco",
    aliases: ["nu disco", "dance disco"],
    seedArtists: ["Chic", "Donna Summer", "Cerrone", "Purple Disco Machine", "Daft Punk", "Dimitri From Paris"],
    relatedArtists: ["Diana Ross", "Bee Gees", "Jamiroquai", "Breakbot", "Folamour"],
    subgenres: ["disco house", "funk"],
    moods: ["feel-good", "groovy", "party"],
  },
  "k-pop": {
    canonicalGenre: "k-pop",
    aliases: ["kpop", "korean pop"],
    seedArtists: ["BTS", "BLACKPINK", "NewJeans", "TWICE", "SEVENTEEN", "aespa"],
    relatedArtists: ["Red Velvet", "LE SSERAFIM", "Stray Kids", "IVE", "EXO", "IU"],
    starterSongs: ["Dynamite", "DDU-DU DDU-DU", "Ditto", "Feel Special"],
    subgenres: ["dance-pop", "r&b", "electropop"],
    moods: ["glossy", "hooky", "high-energy", "beginner-friendly"],
    eras: ["2010s", "2020s"],
    avoidTerms: ["k-pop workout", "kpop mix"],
    notes: "Good default for beginner discovery across major groups and styles.",
  },
  metal: {
    canonicalGenre: "metal",
    aliases: ["heavy metal music", "metal music"],
    seedArtists: ["Metallica", "Iron Maiden", "Black Sabbath", "Judas Priest", "Mastodon", "Gojira"],
    relatedArtists: ["Megadeth", "Slayer", "Pantera", "Tool", "System Of A Down", "Dream Theater"],
    starterSongs: ["Master of Puppets", "Painkiller", "War Pigs", "Hallowed Be Thy Name"],
    subgenres: ["heavy metal", "thrash metal", "progressive metal"],
    moods: ["heavy", "aggressive", "epic"],
    eras: ["classic", "modern"],
    avoidTerms: ["metal workout", "epic metal mix"],
    notes: "Beginner-friendly entry point leaning canonical and accessible.",
  },
  "indie rock": {
    canonicalGenre: "indie rock",
    aliases: ["indie", "alternative indie rock"],
    seedArtists: ["Arctic Monkeys", "The Strokes", "Phoenix", "Vampire Weekend", "The National", "Tame Impala"],
    relatedArtists: ["Interpol", "Yeah Yeah Yeahs", "Foals", "Two Door Cinema Club", "MGMT", "The Killers"],
    starterSongs: ["Do I Wanna Know?", "Last Nite", "1901", "Lisztomania"],
    subgenres: ["alt rock", "post-punk revival", "indie pop"],
    moods: ["cool", "anthemic", "guitar-driven"],
  },
  jazz: {
    canonicalGenre: "jazz",
    aliases: ["jazz music", "getting into jazz"],
    seedArtists: ["Miles Davis", "John Coltrane", "Bill Evans", "Herbie Hancock", "Charles Mingus", "Ella Fitzgerald"],
    relatedArtists: ["Chet Baker", "Thelonious Monk", "Wayne Shorter", "Nina Simone", "Art Blakey", "Stan Getz"],
    starterSongs: ["So What", "Take Five", "Blue in Green", "My Favorite Things"],
    subgenres: ["bebop", "modal jazz", "vocal jazz", "hard bop"],
    moods: ["sophisticated", "improvisational", "beginner-friendly"],
    avoidTerms: ["jazz for studying", "smooth jazz sleep"],
    notes: "Good general entry point when the listener wants to start exploring jazz.",
  },
  "hip-hop": {
    canonicalGenre: "hip-hop",
    aliases: ["hip hop", "rap"],
    seedArtists: ["Kendrick Lamar", "A Tribe Called Quest", "OutKast", "Nas", "JAY-Z", "The Notorious B.I.G."],
    relatedArtists: ["J. Cole", "Tyler, The Creator", "MF DOOM", "Snoop Dogg", "Lauryn Hill", "Little Simz"],
    starterSongs: ["Alright", "Electric Relaxation", "N.Y. State of Mind", "Ms. Jackson"],
    subgenres: ["conscious hip-hop", "boom bap", "jazz rap"],
    moods: ["lyrical", "groovy", "confident"],
  },
  "neo-soul": {
    canonicalGenre: "neo-soul",
    aliases: ["neosoul", "modern soul"],
    seedArtists: ["Erykah Badu", "D'Angelo", "Jill Scott", "Maxwell", "Solange", "Anderson .Paak"],
    relatedArtists: ["Lauryn Hill", "Hiatus Kaiyote", "Musiq Soulchild", "Sade", "H.E.R."],
    starterSongs: ["Untitled (How Does It Feel)", "On & On", "Cranes in the Sky", "Golden"],
    subgenres: ["soul", "r&b", "funk"],
    moods: ["warm", "rich", "groovy", "intimate"],
  },
  ambient: {
    canonicalGenre: "ambient",
    aliases: ["ambient music", "atmospheric ambient"],
    seedArtists: ["Brian Eno", "Aphex Twin", "Stars of the Lid", "Tim Hecker", "Nils Frahm", "Hiroshi Yoshimura"],
    relatedArtists: ["Harold Budd", "William Basinski", "Biosphere", "A Winged Victory for the Sullen", "Grouper"],
    starterSongs: ["An Ending (Ascent)", "Xtal", "Says"],
    subgenres: ["drone", "modern classical", "downtempo"],
    moods: ["immersive", "calm", "expansive"],
    avoidTerms: ["meditation music", "sleep sounds", "ambient noise"],
  },
};
